name: Manual CI

on:
  push:
    paths:
      - "manual/*.org"
      - "manual/*.png"
      - "manual/*.jpg"
      - ".github/workflows/Manual-CI.yaml"

jobs:
  build:
    name: Build manual
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build Org
        uses: docker://pandoc/latex:2.19.2.0
        with:
          args: >-
            --resource-path manual
            --from org
            --to latex
            --output SGE-MANUAL.pdf
            manual/SGE-MANUAL.org
