name: Prerelease

on:
  push:
    tags:
      - "v*.*.*-SNAPSHOT"
      - "v*.*.*-SNAPSHOT-*"


jobs:
  jars:
    name: Build jar, shadowJar, javadoc and sources
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: zulu
          cache: gradle
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        shell: bash
        run: ./gradlew --parallel jar shadowJar javadocJar sources
      - name: Check version number
        run: 'diff -q <(java -jar build/libs/sge-*.*.*-exe.jar --version) <(./gradlew properties | grep -F "version" | grep -E "^version:[ \t]*[0-9]+\.[0-9]+\.[0-9]+$" | sed -E "s/^version:[ \t]*([0-9]+\.[0-9]+\.[0-9]+)$/sge \\1/")'
        continue-on-error: true
      - uses: actions/upload-artifact@v2
        name: Upload jar
        with:
          name: jar
          path: build/libs/sge-*.*.*.jar
      - uses: actions/upload-artifact@v2
        name: Upload sources
        with:
          name: sources
          path: build/libs/sge-*.*.*-sources.jar
      - uses: actions/upload-artifact@v2
        name: Upload javadoc
        with:
          name: javadoc
          path: build/libs/sge-*.*.*-javadoc.jar
      - uses: actions/upload-artifact@v2
        name: Upload shadow
        with:
          name: shadow
          path: build/libs/sge-*.*.*-exe.jar


  github_packages:
    name: Release as github package
    needs: jars
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          cache: gradle
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Ensure build/libs/ exists
        run: mkdir -p build/libs/
      - name: Download jar
        uses: actions/download-artifact@v2
        with:
          name: jar
          path: build/libs/
      - name: Download sources
        uses: actions/download-artifact@v2
        with:
          name: sources
          path: build/libs/
      - name: Download javadoc
        uses: actions/download-artifact@v2
        with:
          name: javadoc
          path: build/libs/
      - name: Publish package
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  github_release:
    name: Release on github
    runs-on: ubuntu-20.04
    needs: jars
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
             sge-*.*.*.jar
             sge-*.*.*-exe.jar
             sge-*.*.*-sources.jar
             sge-*.*.*-javadoc.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

