name: Release

on:
  push:
    tags:
      - "v*.*.*"
      - "!v*.*.*-SNAPSHOT"
      - "!v*.*.*-SNAPSHOT-*"


jobs:
  manual:
    name: Build manual
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Build Org
        uses: docker://pandoc/latex:2.19.2.0
        with:
          args: >-
            --from org
            --to latex
            --output SGE-MANUAL.pdf
            SGE-MANUAL.org
      - name: Upload Manual
        uses: actions/upload-artifact@v2
        with:
          name: manual
          path: SGE-MANUAL.pdf
  jars:
    name: Build jar, shadowJar, javadoc and sources
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: zulu
          cache: gradle
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        shell: bash
        run: ./gradlew --parallel jar shadowJar javadocJar sources
      - name: Check version number
        run: 'diff -q <(java -jar build/libs/sge-*.*.*-exe.jar --version) <(./gradlew properties | grep -F "version" | grep -E "^version:[ \t]*[0-9]+\.[0-9]+\.[0-9]+$" | sed -E "s/^version:[ \t]*([0-9]+\.[0-9]+\.[0-9]+)$/sge \\1/")'
        continue-on-error: false
      - uses: actions/upload-artifact@v2
        name: Upload jar
        with:
          name: jar
          path: |
            build/libs/sge-*.*.*.jar
            !build/libs/sge-*.*.*-*.jar
      - uses: actions/upload-artifact@v2
        name: Upload sources
        with:
          name: sources
          path: build/libs/sge-*.*.*-sources.jar
      - uses: actions/upload-artifact@v2
        name: Upload javadoc
        with:
          name: javadoc
          path: build/libs/sge-*.*.*-javadoc.jar
      - uses: actions/upload-artifact@v2
        name: Upload shadow
        with:
          name: shadow
          path: build/libs/sge-*.*.*-exe.jar


  github_packages:
    name: Release as github package
    needs: jars
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: zulu
          cache: gradle
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Ensure build/libs/ exists
        run: mkdir -p build/libs/
      - name: Download jar
        uses: actions/download-artifact@v2
        with:
          name: jar
          path: build/libs/
      - name: Download sources
        uses: actions/download-artifact@v2
        with:
          name: sources
          path: build/libs/
      - name: Download javadoc
        uses: actions/download-artifact@v2
        with:
          name: javadoc
          path: build/libs/
      - name: Publish package
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  github_release:
    name: Release on github
    runs-on: ubuntu-22.04
    needs:
      - jars
      - manual
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          files: |
             jar/sge-*.*.*.jar
             shadow/sge-*.*.*-exe.jar
             sources/sge-*.*.*-sources.jar
             javadoc/sge-*.*.*-javadoc.jar
             manual/SGE-MANUAL.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

